// ============================================================
// PallettAI Studio — Importer
// Parse + validate incoming `.pallettai` project files.
//
// Studio projects travel as JSON — exported from the dashboard as
// `.pallettai.json`, generated by the website grader's converter,
// or written by third-party tooling. This module is the single
// gate those files pass through: parse, structural validation,
// sanitisation, and a normalised project shape the app can hydrate.
//
// A rejected file always comes back with the reason attached —
// `ok: false, errors: [...]` — never as a throw, so the UI can
// show one honest message instead of a stack trace.
//
// Global API (classic script like the other modules):
//   Importer.parseProjectFile(text)          → { ok, project?, errors?, warnings? }
//   Importer.validateProject(obj)            → { ok, errors, warnings, normalized? }
//   Importer.SCHEMA_VERSION
// ============================================================
(function () {
  'use strict';

  const Importer = {};

  const SCHEMA_VERSION = 2;

  /* ---------------- section vocabulary ---------------- */

  // The section types the builder knows. Unknown types are not a
  // rejection — Studio renders forward — but they are surfaced as
  // warnings so an import from a future version is visible.
  const SECTION_TYPES = [
    'hero', 'about', 'services', 'features', 'gallery', 'pricing', 'faq',
    'contact', 'testimonials', 'reviews', 'team', 'menu', 'blog', 'cta',
    'stats', 'timeline', 'booking', 'events', 'shop', 'map', 'footer', 'nav'
  ];

  const LOOKS = [
    'editorial', 'light', 'warm', 'bright', 'dark', 'bold',
    'noir', 'playful', 'techy', 'minimal'
  ];

  const PALETTE_KEYS = ['primary', 'surface', 'text', 'muted', 'accent'];

  /* ---------------- small helpers ---------------- */

  function isPlainObject(v) {
    return !!v && typeof v === 'object' && !Array.isArray(v);
  }

  function strLimit(v, n) {
    return String(v == null ? '' : v).slice(0, n);
  }

  function clampInt(v, lo, hi, dflt) {
    const n = Math.round(Number(v));
    if (!Number.isFinite(n)) return dflt;
    return Math.max(lo, Math.min(hi, n));
  }

  function asArray(v) {
    return Array.isArray(v) ? v : [];
  }

  function hexOrEmpty(v) {
    const s = String(v == null ? '' : v).trim();
    return /^#[0-9a-fA-F]{3,8}$/.test(s) ? s : '';
  }

  function safeExternalUrl(v) {
    const s = String(v == null ? '' : v).trim();
    if (!s) return '';
    if (/^(https?:)\/\//i.test(s)) return s.slice(0, 2000);
    if (/^(mailto:|tel:)/i.test(s)) return s.slice(0, 500);
    return '';
  }

  // Media payloads travel inlined as data URLs. Every other scheme
  // is stripped: an imported project is data, not code.
  function safeDataUrl(v, n) {
    const s = String(v == null ? '' : v).trim();
    if (!s) return '';
    if (/^data:image\/(png|jpeg|jpg|webp|gif|svg\+xml);base64,[A-Za-z0-9+/=]+$/.test(s)) {
      return s.length <= n ? s : '';
    }
    if (/^https:\/\//i.test(s)) return s.slice(0, 2000);
    return '';
  }

  function looksHtml(v) {
    return /<\s*(script|iframe|object|embed|link|meta)/i.test(String(v || ''));
  }

  function seedRandomId(prefix) {
    const rnd = (typeof crypto !== 'undefined' && crypto.getRandomValues)
      ? crypto.getRandomValues(new Uint8Array(6))
      : [Math.floor(Math.random() * 256), Math.floor(Math.random() * 256), Math.floor(Math.random() * 256),
         Math.floor(Math.random() * 256), Math.floor(Math.random() * 256), Math.floor(Math.random() * 256)];
    let s = '';
    for (let i = 0; i < rnd.length; i++) s += rnd[i].toString(36).padStart(2, '0');
    return prefix + s;
  }

  /* ---------------- field validators ---------------- */

  function validateSection(raw, index, errors, warnings) {
    const where = 'sections[' + index + ']';
    if (!isPlainObject(raw)) {
      errors.push(where + ' is not an object');
      return null;
    }
    const out = { id: '', type: '', title: '', body: '', items: [] };
    out.id = strLimit(raw.id || '', 80).replace(/[^a-zA-Z0-9_-]/g, '') || seedRandomId('sec_');
    const type = strLimit(raw.type || raw.section || '', 40).toLowerCase();
    if (!type) {
      errors.push(where + ' has no type');
      return null;
    }
    if (SECTION_TYPES.indexOf(type) === -1) {
      warnings.push(where + ' uses unknown type "' + type + '" — Studio will render it forward, but it may not edit cleanly.');
    }
    out.type = type;
    out.title = strLimit(raw.title || raw.heading || '', 300);
    if (out.title && looksHtml(out.title)) warnings.push(where + '.title contains markup — imported as plain text.');
    out.body = strLimit(raw.body || raw.text || raw.content || '', 20000);
    if (out.body && looksHtml(out.body)) warnings.push(where + '.body contains markup — imported as plain text.');

    // Structured items (menu entries, FAQs, gallery rows) survive as
    // generic {title, body, image} triples so any suite round-trips.
    const items = asArray(raw.items);
    for (let i = 0; i < items.length && i < 60; i++) {
      const it = items[i];
      if (typeof it === 'string') { out.items.push({ title: strLimit(it, 300), body: '', image: '' }); continue; }
      if (!isPlainObject(it)) continue;
      out.items.push({
        title: strLimit(it.title || it.name || it.q || '', 300),
        body: strLimit(it.body || it.text || it.a || it.answer || it.description || '', 4000),
        image: safeDataUrl(it.image || it.img || it.photo || '', 3_000_000)
      });
    }

    // Keep the section's own id-nameable extras (layout variant,
    // emblem, per-section classes) without importing arbitrary keys.
    if (typeof raw.layout === 'string') out.layout = strLimit(raw.layout, 40);
    if (typeof raw.emblem === 'string') out.emblem = strLimit(raw.emblem, 8);

    return out;
  }

  /* ---------------- normaliser ---------------- */

  function normalizeProject(obj, warnings) {
    const site = isPlainObject(obj.site) ? obj.site : {};
    const dna = isPlainObject(site.dna) ? site.dna : {};

    const palette = {};
    const rawPal = isPlainObject(site.palette) ? site.palette : {};
    for (const k of PALETTE_KEYS) {
      const v = hexOrEmpty(rawPal[k]);
      if (v) palette[k] = v;
    }

    const normalized = {
      id: strLimit(obj.id || '', 80).replace(/[^a-zA-Z0-9_-]/g, '') || seedRandomId('proj_'),
      name: strLimit(obj.name || site.name || 'Imported project', 120),
      schemaVersion: SCHEMA_VERSION,
      updatedAt: clampInt(obj.updatedAt, 0, 8.64e15, Date.now()),
      site: {
        name: strLimit(site.name || obj.name || 'Imported project', 120),
        tagline: strLimit(site.tagline || '', 300),
        contact: {
          email: strLimit(site.contact && site.contact.email || '', 200),
          phone: strLimit(site.contact && site.contact.phone || '', 60),
          address: strLimit(site.contact && site.address || (site.contact && site.contact.address) || '', 400)
        },
        sections: [],
        pages: [],
        palette: palette,
        fonts: {
          heading: strLimit(site.fonts && site.fonts.heading || dna.fontDisplay || site.fontDisplay || '', 80),
          body: strLimit(site.fonts && site.fonts.body || dna.font || site.font || '', 80)
        },
        dna: {
          look: LOOKS.indexOf(dna.look) !== -1 ? dna.look : 'editorial',
          radius: clampInt(dna.radius, 0, 48, 12),
          spacing: clampInt(dna.spacing, 48, 200, 104)
        },
        meta: {
          description: strLimit(site.meta && site.meta.description || site.metaDescription || '', 300),
          ogImage: safeDataUrl(site.meta && site.meta.ogImage || '', 3_000_000)
        }
      },
      suites: asArray(obj.suites).filter(function (s) { return isPlainObject(s) && typeof s.type === 'string'; }).slice(0, 20)
    };

    // Sections — the heart of the project. Malformed entries are
    // dropped with a warning, not fatal.
    const sections = asArray(site.sections);
    let dropped = 0;
    for (let i = 0; i < sections.length && normalized.site.sections.length < 60; i++) {
      const s = validateSection(sections[i], i, [], warnings);
      if (s) normalized.site.sections.push(s);
      else dropped++;
    }
    if (dropped > 0) warnings.push(dropped + ' malformed section(s) were dropped.');
    if (!normalized.site.sections.length) {
      warnings.push('The project has no sections — Studio will open it with an empty canvas.');
    }

    // Multi-page exports: keep page names/paths, and each page's
    // sections ride through the same validator.
    const pages = asArray(site.pages);
    for (let i = 0; i < pages.length && i < 12; i++) {
      const p = pages[i];
      if (!isPlainObject(p)) continue;
      const page = {
        name: strLimit(p.name || '', 120),
        path: strLimit(p.path || '', 200).replace(/[^a-zA-Z0-9\-_/.]/g, ''),
        sections: []
      };
      const psecs = asArray(p.sections);
      for (let j = 0; j < psecs.length && page.sections.length < 60; j++) {
        const s = validateSection(psecs[j], j, [], warnings);
        if (s) page.sections.push(s);
      }
      if (page.name || page.path) normalized.site.pages.push(page);
    }

    return normalized;
  }

  /* ---------------- validation ---------------- */

  function validateProject(obj) {
    const errors = [];
    const warnings = [];

    if (!isPlainObject(obj)) {
      return { ok: false, errors: ['File is not a JSON object'], warnings: warnings };
    }

    // Accept the two shapes Studio knows: a bare project, or the
    // grader converter's envelope { kind: 'pallettai.project', project }.
    let proj = obj;
    if (isPlainObject(obj.project) && (obj.kind === 'pallettai.project' || obj.format === 'pallettai')) {
      proj = obj.project;
    }

    if (!isPlainObject(proj.site)) {
      errors.push('Missing site — a .pallettai project needs { site: { sections: [...] } }');
      return { ok: false, errors: errors, warnings: warnings };
    }
    if (!Array.isArray(proj.site.sections)) {
      errors.push('site.sections is missing or not a list');
      return { ok: false, errors: errors, warnings: warnings };
    }

    // Media budget: inlined photos are the realistic way a project
    // file gets enormous. Cap the sum so a fat file fails with a
    // reason rather than freezing the renderer.
    const MEDIA_CAP = 40 * 1024 * 1024;
    let mediaBytes = 0;
    const walkMedia = function (s) {
      if (!isPlainObject(s)) return;
      for (const it of asArray(s.items)) {
        if (isPlainObject(it) && typeof it.image === 'string' && it.image.startsWith('data:')) {
          mediaBytes += it.image.length;
        }
      }
      if (typeof s.image === 'string' && s.image.startsWith('data:')) mediaBytes += s.image.length;
    };
    for (const s of asArray(proj.site.sections)) walkMedia(s);
    for (const p of asArray(proj.site.pages)) for (const s of asArray(p.sections)) walkMedia(s);
    if (mediaBytes > MEDIA_CAP) {
      errors.push('Inlined media is ~' + Math.round(mediaBytes / 1048576) + ' MB — the limit for a .pallettai file is ' + (MEDIA_CAP / 1048576) + ' MB. Export with linked images instead.');
      return { ok: false, errors: errors, warnings: warnings };
    }

    const normalized = normalizeProject(proj, warnings);

    return {
      ok: errors.length === 0,
      errors: errors,
      warnings: warnings,
      normalized: normalized
    };
  }

  /* ---------------- parse entry ---------------- */

  /**
   * parseProjectFile(text)
   * @param {string} text  raw contents of a .pallettai / .pallettai.json file
   * @returns {{ ok: boolean, project?: object, errors?: string[], warnings?: string[] }}
   */
  Importer.parseProjectFile = function (text) {
    if (typeof text !== 'string' || !text.trim()) {
      return { ok: false, errors: ['File is empty'], warnings: [] };
    }
    if (text.length > 48 * 1024 * 1024) {
      return { ok: false, errors: ['File is too large to import (limit ~48 MB)'], warnings: [] };
    }
    let obj;
    try {
      obj = JSON.parse(text);
    } catch (e) {
      const msg = String(e && e.message || 'Invalid JSON');
      return { ok: false, errors: ['Not valid JSON: ' + msg.slice(0, 200)], warnings: [] };
    }
    const res = validateProject(obj);
    if (!res.ok) return { ok: false, errors: res.errors, warnings: res.warnings };
    return { ok: true, project: res.normalized, errors: [], warnings: res.warnings };
  };

  Importer.validateProject = validateProject;
  Importer.SCHEMA_VERSION = SCHEMA_VERSION;
  Importer.SECTION_TYPES = SECTION_TYPES;

  if (typeof module !== 'undefined' && module.exports) module.exports = Importer;
})();
