'use strict';
// ============================================================
// PallettAI Studio — legal & GDPR compliance generator
// Privacy/terms documents + a privacy-first consent banner.
// ------------------------------------------------------------
//   1. generatePrivacyPolicy(siteDetails) → [{name, content}, …]
//      Builds complete privacy.html and terms.html documents from
//      what the business actually is: business type decides which
//      data points, payments, accounts and retention rows exist;
//      region decides the governing regime (UK GDPR / EU GDPR /
//      CCPA-CPRA / PIPEDA / Australian Privacy Act / generic) and
//      the rights + governing-law clauses. The two pages cross-link.
//
//   2. generateCookieConsentScript(options) → string
//      A zero-cookie banner: the consent decision lives in
//      localStorage, never document.cookie. Honours Do Not Track
//      (navigator/window/msDoNotTrack) and Global Privacy Control
//      as an automatic opt-out — those visitors are never prompted
//      because the answer is already known. GDPR: nothing
//      non-essential loads before an explicit Accept, Decline is
//      offered equally, and the choice can be withdrawn at any time
//      via window.__paiConsent. CCPA: optional "Do Not Sell or
//      Share" link plus GPC opt-out above.
//
// ---- what this file guarantees ----------------------------------
// 1. THE POLICY NEVER CLAIMS A PRACTICE THE CONFIG DOESN'T SET.
//    No shop flag → no orders/shipments clause; no analytics flag →
//    no analytics processor named. A policy that lies about data
//    handling is worse than no policy.
// 2. EVERY INTERPOLATED STRING IS ESCAPED — a hostile business name
//    becomes text in the document, never live markup.
// 3. THE CONSENT SCRIPT SETS NO COOKIES, EVER. It reads/writes one
//    localStorage key and loads nothing itself; the analytics starter
//    (window.__paiAnalytics, the hook exported sites already use) is
//    called only after an explicit, stored Accept.
// 4. THIS IS A STARTING DOCUMENT, NOT LEGAL ADVICE — each generated
//    page carries that note in an HTML comment and in the footer, the
//    same posture data/legal.js takes.
//
// Pure string generation: no network, no DOM, no storage here.
// ============================================================

// ---- escaping (same contract as Builder.esc) ------------------------
const esc = (s) => String(s == null ? '' : s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;').replace(/'/g, '&#39;');

const NOTE = '<!-- Generated by PallettAI Studio from this site\u2019s own details. '
  + 'It is a starting document, not legal advice: have it reviewed before you rely on it. -->';

// ============================================================
// Fact derivation — one place that decides what is true
// ============================================================

const TYPE_ALIASES = {
  ecommerce: 'ecommerce', shop: 'ecommerce', store: 'ecommerce', retail: 'ecommerce',
  saas: 'saas', software: 'saas', app: 'saas', platform: 'saas',
  service: 'service', agency: 'service', local: 'service', professional: 'service',
  content: 'content', blog: 'content', media: 'content', publication: 'content',
  nonprofit: 'nonprofit', charity: 'nonprofit',
  portfolio: 'portfolio'
};

const REGION_ALIASES = {
  uk: 'UK', gb: 'UK', 'united kingdom': 'UK',
  eu: 'EU', eea: 'EU', europe: 'EU',
  us: 'US', usa: 'US',
  'us-ca': 'US-CA', california: 'US-CA', 'us-ca-gdpr': 'US-CA',
  ca: 'CA', canada: 'CA',
  au: 'AU', australia: 'AU'
};

function normalizeType(raw) {
  const k = String(raw || '').trim().toLowerCase();
  return TYPE_ALIASES[k] || 'service';
}

function normalizeRegion(raw) {
  const k = String(raw || '').trim().toLowerCase();
  return REGION_ALIASES[k] || 'generic';
}

// The regime paragraph + rights list for each supported region.
// Unknown regions fall to 'generic' — which claims NO specific law,
// because inventing a jurisdiction the business isn't subject to is
// exactly the failure this module exists to prevent.
function regimeFor(region) {
  switch (region) {
    case 'UK':
      return {
        laws: 'the UK GDPR and the Data Protection Act 2018',
        authority: 'the Information Commissioner\u2019s Office (ICO)',
        rights: [
          'request access to the personal data we hold about you',
          'have inaccurate data corrected',
          'request erasure (the \u201cright to be forgotten\u201d) in the circumstances set out in law',
          'restrict or object to how we use your data, including objecting to direct marketing',
          'receive your data in a portable, machine-readable format',
          'withdraw any consent you have given at any time'
        ],
        complaint: 'You can lodge a complaint with the Information Commissioner\u2019s Office at ico.org.uk.',
        governingLaw: 'the laws of England and Wales'
      };
    case 'EU':
      return {
        laws: 'the General Data Protection Regulation (GDPR, Regulation (EU) 2016/679)',
        authority: 'your national data protection authority',
        rights: [
          'access, rectification and erasure of your data',
          'restriction of processing and data portability',
          'object to processing, including profiling based on legitimate interests',
          'withdraw consent at any time without affecting prior processing',
          'not be subject to decisions based solely on automated processing that significantly affect you'
        ],
        complaint: 'You have the right to lodge a complaint with your national supervisory authority.',
        governingLaw: 'the laws of the European Union member state in which the business is established'
      };
    case 'US-CA':
      return {
        laws: 'the California Consumer Privacy Act (CCPA) as amended by the CPRA',
        authority: 'the California Attorney General and the California Privacy Protection Agency',
        rights: [
          'know the categories and specific pieces of personal information we collect and the purposes we use them for',
          'delete or correct personal information we have collected, subject to statutory exceptions',
          'opt out of the \u201csale\u201d or \u201csharing\u201d of your personal information for cross-context behavioural advertising',
          'limit the use of sensitive personal information',
          'not be discriminated against for exercising any of these rights'
        ],
        complaint: 'You may submit a request or complaint to the California Privacy Protection Agency at cppa.ca.gov.',
        governingLaw: 'the laws of the State of California',
        ccpa: true
      };
    case 'US':
      return {
        laws: 'applicable US state privacy laws, including the California Consumer Privacy Act (CCPA) as amended by the CPRA for California residents',
        authority: 'the relevant state attorney general',
        rights: [
          'know the categories of personal information collected and how it is used',
          'delete or correct personal information, with statutory exceptions',
          'opt out of any sale or sharing of personal information for cross-context advertising',
          'exercise these rights without discriminatory treatment'
        ],
        complaint: 'Requests can be made to the contact address below; California residents may also contact the California Privacy Protection Agency.',
        governingLaw: 'the laws of the State in which the business is registered, applicable US federal law',
        ccpa: true
      };
    case 'CA':
      return {
        laws: 'the Personal Information Protection and Electronic Documents Act (PIPEDA)',
        authority: 'the Office of the Privacy Commissioner of Canada (OPC)',
        rights: [
          'access the personal information we hold about you',
          'challenge its accuracy and have it corrected when needed',
          'withdraw your consent to collection, use or disclosure at any time',
          'file a complaint with the Office of the Privacy Commissioner of Canada'
        ],
        complaint: 'You can complain to the Office of the Privacy Commissioner of Canada at priv.gc.ca.',
        governingLaw: 'the laws of the Province of Ontario and the applicable laws of Canada'
      };
    case 'AU':
      return {
        laws: 'the Privacy Act 1988 (Cth) and the Australian Privacy Principles (APPs)',
        authority: 'the Office of the Australian Information Commissioner (OAIC)',
        rights: [
          'access personal information we hold about you and correct it if it is inaccurate',
          'make a complaint about how your information has been handled',
          'withdraw consent for optional uses such as marketing at any time'
        ],
        complaint: 'You can complain to the Office of the Australian Information Commissioner at oaic.gov.au.',
        governingLaw: 'the laws of the State of New South Wales, Australia'
      };
    default:
      return {
        laws: 'the data protection laws that apply where you live',
        authority: 'your local data protection regulator',
        rights: [
          'access, correction and deletion of your personal information, where those rights apply to you',
          'object to or restrict certain processing',
          'withdraw consent at any time for processing based on consent'
        ],
        complaint: 'Contact us using the details below and we will route your request appropriately.',
        governingLaw: 'the laws applicable at the business\u2019s principal place of business'
      };
  }
}

// What the business actually collects/does. Flags override the
// type-derived defaults; false flags always win so an explicitly
// switched-off feature can never sneak back into the prose.
function policyFacts(siteDetails) {
  const d = siteDetails || {};
  const type = normalizeType(d.businessType || d.type);
  const region = normalizeRegion(d.region || d.country);
  const flags = d.flags || d.collects || {};

  const has = (key, typeDefault) => {
    if (flags[key] === false || d[key] === false) return false;
    if (flags[key] === true || d[key] === true) return true;
    return !!typeDefault;
  };

  const facts = {
    name: String(d.businessName || d.name || 'the site operator'),
    domain: String(d.domain || deriveDomain(d.url) || ''),
    url: String(d.url || (d.domain ? 'https://' + d.domain : '')),
    email: String(d.email || d.contactEmail || ''),
    type,
    region,
    regime: regimeFor(region),
    effective: String(d.effectiveDate || defaultDate()),

    shop: has('shop', type === 'ecommerce'),
    accounts: has('accounts', type === 'saas'),
    forms: has('forms', type !== 'portfolio'),
    newsletter: has('newsletter', false),
    comments: has('comments', false),
    analytics: has('analytics', false),
    booking: has('booking', false),
    chat: has('chat', false),
    donations: has('donations', type === 'nonprofit'),

    paymentProvider: String(d.paymentProvider || flags.paymentProvider || ''),
    formProvider: detectFormProvider(d.formEndpoint || d.forms || flags.formEndpoint || ''),
    analyticsProvider: String(d.analyticsProvider || flags.analyticsProvider || ''),
    hosting: String(d.hosting || flags.hosting || '')
  };
  // Shop implies payments even if nobody set the flag.
  if (facts.shop) facts.payments = true;
  return facts;
}

function deriveDomain(url) {
  const m = String(url || '').match(/^https?:\/\/([^/?#]+)/i);
  return m ? m[1].replace(/^www\./, '') : '';
}

// Only ever names a service the config literally points at.
function detectFormProvider(raw) {
  const v = String(raw || '').trim();
  if (!v) return '';
  if (/formspree\.io/i.test(v)) return 'Formspree';
  if (/web3forms\.com/i.test(v)) return 'Web3Forms';
  if (/getform\.io/i.test(v)) return 'GetForm';
  if (/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(v)) return 'an email delivery service';
  if (/^https?:\/\//i.test(v)) return 'a third-party form service';
  return '';
}

function defaultDate() {
  const d = new Date();
  if (Number.isNaN(d.getTime())) return '';
  return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
}

// ============================================================
// Task 3.1 — privacy.html + terms.html
// ============================================================
//
// Returns zip-ready file entries ({name, content}) so the export
// pipeline can consume them without a wrapper object.
function generatePrivacyPolicy(siteDetails) {
  const f = policyFacts(siteDetails);
  return [
    { name: 'privacy.html', content: privacyDocument(f) },
    { name: 'terms.html', content: termsDocument(f) }
  ];
}

// ---- shared page chrome --------------------------------------------
// Static styles only: these documents animate nothing, so there is no
// keyframe to reduce-wrap and no motion for the banner below to fight.
function pageDoc(title, f, body) {
  const name = esc(f.name);
  const domainLine = f.domain ? esc(f.domain) : esc(f.url || f.name);
  return '<!DOCTYPE html>\n<html lang="en">\n<head>\n'
    + '<meta charset="utf-8">\n'
    + '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
    + '<title>' + title + ' \u2014 ' + name + '</title>\n'
    + '<style>\n'
    + ':root{color-scheme:light dark;--t:#0b1220;--m:#4b5563;--l:#e5e7eb;--a:#2f6fed}'
    + '@media (prefers-color-scheme:dark){:root{--t:#e8ecf5;--m:#9aa4b6;--l:#28324a;--a:#7aa5ff}}'
    + 'body{max-width:760px;margin:0 auto;padding:2rem 1.2rem 4rem;color:var(--t);'
    + 'font:16px/1.65 system-ui,-apple-system,"Segoe UI",sans-serif}'
    + 'h1{font-size:1.9rem;letter-spacing:-.02em;margin:.2rem 0 .4rem}'
    + 'h2{font-size:1.15rem;margin:2rem 0 .5rem;letter-spacing:-.01em}'
    + 'p,li{color:var(--t)}'
    + '.meta{color:var(--m);font-size:.85rem;margin:0 0 1.4rem}'
    + 'ul{padding-left:1.2rem}li{margin:.3rem 0}'
    + 'a{color:var(--a)}'
    + 'footer{margin-top:3rem;padding-top:1rem;border-top:1px solid var(--l);'
    + 'color:var(--m);font-size:.8rem;display:flex;gap:1rem;flex-wrap:wrap}'
    + '.disc{color:var(--m);font-size:.82rem;margin-top:2rem}'
    + '</style>\n'
    + '</head>\n<body>\n'
    + '<main>\n' + body + '\n</main>\n'
    + '<footer>'
    + '<a href="privacy.html">Privacy Policy</a>'
    + '<a href="terms.html">Terms of Use</a>'
    + '<span>' + domainLine + '</span>'
    + '</footer>\n'
    + NOTE + '\n'
    + '</body>\n</html>\n';
}

function contactBlock(f) {
  if (!f.email) return '';
  return '<p>Privacy questions: <a href="mailto:' + esc(f.email) + '">' + esc(f.email) + '</a></p>';
}

// ---- data-point rows per business type ------------------------------
function collectedSections(f) {
  const rows = [];
  rows.push('<h2>What we collect</h2>');
  const items = [];

  if (f.forms) {
    items.push('the details you send through our contact or enquiry form (typically your name, '
      + 'email address and whatever you write to us)');
  }
  if (f.accounts) {
    items.push('account details you provide when registering (name, email address and password \u2014 '
      + 'passwords are stored only as hashes)');
    items.push('billing details for your subscription and basic usage data needed to run and secure the service');
  }
  if (f.shop) {
    items.push('order details: the products you buy, your name, delivery address and contact details');
    items.push('payment information \u2014 processed by '
      + (f.paymentProvider ? esc(f.paymentProvider) : 'our payment processor')
      + '; we never see or store your full card number');
  }
  if (f.donations) {
    items.push('donation details (amount, name and receipt email) processed by our payment provider');
  }
  if (f.newsletter) {
    items.push('your email address and subscription preferences if you sign up to our newsletter');
  }
  if (f.comments) {
    items.push('the content of comments you leave and the name you sign them with');
  }
  if (f.booking) {
    items.push('appointment or booking details (date, time and contact information)');
  }
  if (f.analytics) {
    items.push('standard technical data such as pages visited, device and browser type, general location '
      + 'and referral source, collected by '
      + (f.analyticsProvider ? esc(f.analyticsProvider) : 'our analytics provider')
      + ' to help us understand how the site is used');
  }
  items.push('technical data the server logs automatically, such as IP address, requested URL and request time, '
    + 'kept for security and abuse prevention');

  items.forEach((i) => { rows.push('<li>' + i + '</li>'); });
  rows.push('</ul>');
  // Open the list right after the heading.
  return rows[0] + '<ul>' + rows.slice(1).join('');
}

function privacyDocument(f) {
  const r = f.regime;
  const name = esc(f.name);
  const parts = [];

  parts.push('<h1>Privacy Policy</h1>');
  parts.push('<p class="meta">Effective ' + esc(f.effective)
    + (f.domain ? ' \u00b7 ' + esc(f.domain) : '') + '</p>');

  parts.push('<h2>Who we are</h2>');
  parts.push('<p>' + name + (f.domain ? ' (' + esc(f.domain) + ')' : '')
    + ' operates this website. In this policy, \u201cwe\u201d means ' + name
    + '. We are the controller of the personal data described here under ' + esc(r.laws) + '.</p>');
  if (f.email) {
    parts.push('<p>Contact: <a href="mailto:' + esc(f.email) + '">' + esc(f.email) + '</a></p>');
  }

  parts.push(collectedSections(f));

  parts.push('<h2>Why we use it</h2><ul>');
  if (f.forms || f.booking) parts.push('<li>To answer enquiries and deliver the services you ask for (steps before a contract, or performance of a contract).</li>');
  if (f.shop || f.donations) parts.push('<li>To process orders and donations, take payment and send receipts (performance of a contract).</li>');
  if (f.accounts) parts.push('<li>To create and secure your account and provide the service (performance of a contract and legitimate interests in keeping the service safe).</li>');
  if (f.newsletter) parts.push('<li>To send the newsletter you subscribed to \u2014 based on your consent, withdrawable in every email.</li>');
  if (f.analytics) parts.push('<li>To understand aggregated usage and improve the site (legitimate interests; loaded only after you consent where required).</li>');
  parts.push('<li>To protect the site against abuse and keep it secure (legitimate interests).</li>');
  parts.push('</ul>');

  parts.push('<h2>Cookies and local storage</h2>');
  parts.push('<p>This site is privacy-first: the consent banner stores your choice in your browser\u2019s '
    + 'local storage rather than a cookie, and the site itself sets no tracking cookies before you agree to them.'
    + (f.analytics ? ' Analytics runs only after you accept.' : ' No analytics or advertising cookies are used.') + '</p>');
  if (f.shop || f.accounts) {
    parts.push('<p>Strictly necessary storage may be used to keep you signed in or to hold your basket '
      + 'while you shop; these do not require consent because the site cannot function without them.</p>');
  }

  parts.push('<h2>Who we share it with</h2><ul>');
  if (f.hosting) parts.push('<li>' + esc(f.hosting) + ' \u2014 hosting this website.</li>');
  else parts.push('<li>Our hosting provider, which runs this website.</li>');
  if (f.formProvider) parts.push('<li>' + esc(f.formProvider) + ' \u2014 delivering form submissions to us.</li>');
  if (f.shop || f.donations) parts.push('<li>' + (f.paymentProvider ? esc(f.paymentProvider) : 'Our payment processor')
    + ' \u2014 taking payment; they handle card data under PCI-DSS.</li>');
  if (f.analytics && f.analyticsProvider) parts.push('<li>' + esc(f.analyticsProvider) + ' \u2014 anonymised usage statistics.</li>');
  if (f.chat) parts.push('<li>Our live-chat provider \u2014 answering messages you send.</li>');
  if (f.newsletter) parts.push('<li>Our email newsletter provider \u2014 sending the newsletter you asked for.</li>');
  parts.push('<li>Professional advisers and authorities where the law requires us to disclose information.</li>');
  parts.push('</ul>');
  parts.push('<p>We do <strong>not</strong> sell your personal information.</p>');

  parts.push('<h2>How long we keep it</h2><ul>');
  if (f.shop || f.donations) parts.push('<li>Order and donation records: up to 7 years, to meet tax and accounting duties.</li>');
  if (f.accounts) parts.push('<li>Account data: while your account is open, then deleted or anonymised within 90 days of closure.</li>');
  if (f.forms || f.booking) parts.push('<li>Enquiries and booking requests: up to 12 months after we last correspond.</li>');
  if (f.newsletter) parts.push('<li>Newsletter subscription: until you unsubscribe.</li>');
  if (f.analytics) parts.push('<li>Analytics data: for the retention period set by '
    + (f.analyticsProvider ? esc(f.analyticsProvider) : 'our analytics provider') + '.</li>');
  parts.push('<li>Server logs: for up to 30 days, for security.</li>');
  parts.push('</ul>');

  parts.push('<h2>Your rights</h2>');
  parts.push('<p>Under ' + esc(r.laws) + ' you may:</p><ul>');
  r.rights.forEach((right) => { parts.push('<li>' + right + '</li>'); });
  parts.push('</ul>');
  parts.push('<p>' + esc(r.complaint) + '</p>');
  if (r.ccpa) {
    parts.push('<p>We do not sell your personal information. To make a rights request as a '
      + (f.region === 'US-CA' ? 'California resident' : 'US resident')
      + ', contact us using the address below and we will respond within the time the law allows.</p>');
  }

  if (f.region === 'UK' || f.region === 'EU' || f.region === 'AU') {
    parts.push('<h2>International transfers</h2>');
    parts.push('<p>Where our providers process data outside your country, we rely on the safeguards the law '
      + 'provides for such transfers (for example adequacy decisions or standard contractual clauses).</p>');
  }

  parts.push('<h2>Children</h2>');
  parts.push('<p>This site is not directed at children under 16, and we do not knowingly collect their data. '
    + 'If you believe a child has provided information to us, contact us and we will delete it.</p>');

  parts.push('<h2>Changes to this policy</h2>');
  parts.push('<p>We may update this page when our practices or the law change. The effective date at the top '
    + 'shows when the current version took effect.</p>');

  parts.push('<h2>Contact</h2>');
  parts.push(contactBlock(f) || '<p>Use the contact details published on this site to reach us.</p>');
  parts.push('<p>Read our <a href="terms.html">Terms of Use</a> for the rules that apply to using this site.</p>');
  parts.push('<p class="disc">This document was generated from the site\u2019s own configuration and is a '
    + 'starting point, not legal advice.</p>');

  return pageDoc('Privacy Policy', f, parts.join('\n'));
}

function termsDocument(f) {
  const r = f.regime;
  const name = esc(f.name);
  const parts = [];

  parts.push('<h1>Terms of Use</h1>');
  parts.push('<p class="meta">Effective ' + esc(f.effective)
    + (f.domain ? ' \u00b7 ' + esc(f.domain) : '') + '</p>');

  parts.push('<h2>1. About these terms</h2>');
  parts.push('<p>These terms govern your use of this website, operated by ' + name
    + (f.domain ? ' (' + esc(f.domain) + ')' : '') + '. By using the site you accept them. '
    + 'If you do not agree, please do not use the site.</p>');

  parts.push('<h2>2. What we offer</h2>');
  if (f.shop) {
    parts.push('<p>We sell goods through this website. Product descriptions and prices are shown on the site; '
      + 'an order is accepted when we confirm it. Images are illustrative and stock may vary.</p>');
  } else if (f.accounts) {
    parts.push('<p>We provide a subscription service. Your account is personal to you, and you are '
      + 'responsible for keeping your login credentials confidential.</p>');
  } else if (f.donations) {
    parts.push('<p>We accept donations through this website. Donations are voluntary and, once made, are '
      + 'not refundable except where the law requires otherwise.</p>');
  } else if (f.type === 'content') {
    parts.push('<p>We publish articles and resources on this website for general information. '
      + 'Nothing on the site constitutes professional advice tailored to your circumstances.</p>');
  } else if (f.type === 'portfolio') {
    parts.push('<p>We showcase our work on this website. Enquiries about commissions are handled '
      + 'individually and are not governed by these terms until a separate agreement is signed.</p>');
  } else {
    parts.push('<p>We provide information and enquiry services through this website. '
      + 'Any engagement beyond the site is confirmed separately in writing.</p>');
  }

  if (f.accounts || f.newsletter) {
    parts.push('<h2>3. Accounts and registrations</h2>');
    parts.push('<p>You must provide accurate information and keep it up to date. Tell us promptly if you '
      + 'suspect unauthorised use of your account. We may suspend accounts that breach these terms.</p>');
  }

  if (f.shop) {
    const n = (f.accounts || f.newsletter) ? '4' : '3';
    parts.push('<h2>' + n + '. Orders, payment and delivery</h2>');
    parts.push('<p>Prices include applicable taxes unless stated otherwise. Payment is taken through '
      + (f.paymentProvider ? esc(f.paymentProvider) : 'our payment processor')
      + ' at checkout. Delivery options, timeframes and costs are shown before you order. '
      + 'Statutory cancellation and refund rights apply to consumer purchases and are unaffected by these terms.</p>');
  }

  if (f.comments) {
    const n = f.shop ? '5' : ((f.accounts || f.newsletter) ? '4' : '3');
    parts.push('<h2>' + n + '. Comments and contributions</h2>');
    parts.push('<p>You are responsible for what you post. Comments must not be unlawful, defamatory, '
      + 'spam or infringing. We may remove comments that breach these rules.</p>');
  }

  const useN = parts.filter((p) => /^<h2>/.test(p)).length + 1;
  parts.push('<h2>' + useN + '. Acceptable use</h2>');
  parts.push('<p>You must not misuse the site: no attempts to gain unauthorised access, no scraping that '
    + 'disrupts the service, no injection of malicious code, and no use that breaks the law or infringes '
    + 'the rights of others.</p>');

  parts.push('<h2>' + (useN + 1) + '. Intellectual property</h2>');
  parts.push('<p>Unless a page says otherwise, the site\u2019s text, design and graphics belong to '
    + name + ' or are used with permission. You may view and print pages for personal, non-commercial use. '
    + 'Republication requires our written consent.</p>');

  parts.push('<h2>' + (useN + 2) + '. Links to other sites</h2>');
  parts.push('<p>The site may link to third-party websites we do not control. Those sites carry their own '
    + 'terms and privacy policies, and we are not responsible for their content.</p>');

  parts.push('<h2>' + (useN + 3) + '. Disclaimers and liability</h2>');
  parts.push('<p>The site is provided \u201cas is\u201d. To the fullest extent the law allows, we give no '
    + 'warranties that the site will be uninterrupted, error-free or fit for a particular purpose. '
    + 'Nothing in these terms limits liability that cannot be limited by law, including liability for '
    + 'fraud or death or personal injury caused by negligence.</p>');

  parts.push('<h2>' + (useN + 4) + '. Changes</h2>');
  parts.push('<p>We may update these terms. The effective date at the top shows when the current version '
    + 'took effect. Continued use of the site after a change means you accept it.</p>');

  parts.push('<h2>' + (useN + 5) + '. Governing law</h2>');
  parts.push('<p>These terms are governed by ' + esc(r.governingLaw)
    + ', and the courts of that jurisdiction have exclusive jurisdiction, subject to any mandatory '
    + 'consumer protections that apply where you live.</p>');

  parts.push('<h2>' + (useN + 6) + '. Contact</h2>');
  parts.push(contactBlock(f) || '<p>Use the contact details published on this site to reach us.</p>');
  parts.push('<p>How we handle your data is described in our <a href="privacy.html">Privacy Policy</a>.</p>');
  parts.push('<p class="disc">This document was generated from the site\u2019s own configuration and is a '
    + 'starting point, not legal advice.</p>');

  return pageDoc('Terms of Use', f, parts.join('\n'));
}

// ============================================================
// Task 3.2 — zero-cookie consent banner script
// ============================================================
//
// NOTE ON CONSTRUCTION: everything below this line is assembled as
// one string of JS source, so comments about the *generated* script
// live above, never between the concatenation lines — a module-level
// // comment dropped between two + '…' lines would itself become
// source text in the output.
//
//
// options = {
//   storageKey?    localStorage key (default 'site_consent')
//   privacyUrl?    default 'privacy.html'
//   termsUrl?      default 'terms.html'
//   doNotSellUrl?  CCPA link; shown when region is US/US-CA
//   region?        'US' | 'US-CA' | 'UK' | 'EU' | …
//   analyticsHook? window function to start after Accept
//                  (default '__paiAnalytics' — the hook exports use)
//   bannerText?    copy override
// }
//
// Returns a self-contained IIFE string. Behaviour:
//   stored Accept        → start analytics, no banner
//   stored Decline       → nothing, no banner
//   DNT or GPC signal    → treated as Decline, banner suppressed
//                          (the answer is already known; asking again
//                          would be a dark pattern)
//   nothing stored       → banner with equal Accept / Decline
//
// It never writes document.cookie and never fetches anything itself.
function generateCookieConsentScript(options) {
  const o = options || {};
  const cfg = {
    key: String(o.storageKey || 'site_consent').replace(/[^\w:.-]/g, '') || 'site_consent',
    privacy: String(o.privacyUrl || 'privacy.html'),
    terms: String(o.termsUrl || 'terms.html'),
    doNotSell: o.doNotSellUrl ? String(o.doNotSellUrl) : '',
    ccpa: ['US', 'US-CA'].indexOf(normalizeRegion(o.region)) !== -1,
    hook: String(o.analyticsHook || '__paiAnalytics').replace(/[^\w.$]/g, '') || '__paiAnalytics',
    text: String(o.bannerText || 'We use cookies only with your consent. You can accept or decline, '
      + 'and change your mind at any time.')
  };

  // Every string below is JS SOURCE in the output: config arrives via
  // JSON.stringify (never markup), copy enters the DOM via textContent,
  // and no comment may sit between two concatenation lines.
  return '(function(){'
    + 'var CFG=' + JSON.stringify(cfg) + ';'
    + 'var el=null;'
    + 'var choice=null;'
    + 'function read(){try{return localStorage.getItem(CFG.key);}catch(e){return null;}}'
    + 'function write(v){try{if(v===null)localStorage.removeItem(CFG.key);else localStorage.setItem(CFG.key,v);}catch(e){}}'
    // DNT (all three spellings) + GPC: visitor-expressed opt-outs,
    // honoured without prompting — the answer is already known.
    + 'function optOut(){'
    + 'try{if(String(navigator.doNotTrack)==="1"||String(window.doNotTrack)==="1"'
    + '||String(navigator.msDoNotTrack)==="1")return true;}catch(e){}'
    + 'try{if(navigator.globalPrivacyControl===true)return true;}catch(e){}'
    + 'return false;'
    + '}'
    + 'function start(){var fn=window[CFG.hook];if(typeof fn==="function"){try{fn();}catch(e){}}}'
    + 'function stop(){var fn=window[CFG.hook+"Stop"];if(typeof fn==="function"){try{fn();}catch(e){}}}'
    + 'function hide(){if(el&&el.parentNode)el.parentNode.removeChild(el);el=null;}'
    // The single state writer: stored value, side effect, banner out.
    + 'function decide(v){choice=v;write(v);if(v==="granted")start();else stop();hide();}'
    + 'function show(){'
    + 'if(el||choice)return;'
    + 'el=document.createElement("div");'
    + 'el.setAttribute("role","dialog");'
    + 'el.setAttribute("aria-modal","false");'
    + 'el.setAttribute("aria-label","Cookie consent");'
    + 'el.style.cssText="position:fixed;left:12px;right:12px;bottom:12px;z-index:9999;'
    + 'max-width:560px;margin:0 auto;padding:14px 16px;border-radius:12px;'
    + 'background:#0b1220;color:#e8ecf5;box-shadow:0 12px 40px rgba(0,0,0,.35);'
    + 'font:14px/1.5 system-ui,sans-serif;display:flex;gap:12px;flex-wrap:wrap;align-items:center";'
    + 'var msg=document.createElement("span");'
    + 'msg.style.cssText="flex:1 1 240px";'
    + 'msg.textContent=CFG.text;'
    + 'el.appendChild(msg);'
    + 'function btn(label,solid){'
    + 'var b=document.createElement("button");'
    + 'b.type="button";b.textContent=label;'
    + 'b.style.cssText="padding:8px 16px;border-radius:8px;font:inherit;font-weight:600;cursor:pointer;"'
    + '+(solid?"border:1px solid #2f6fed;background:#2f6fed;color:#fff"'
    + ':"border:1px solid #4b5563;background:transparent;color:#e8ecf5")'
    + '+";flex:0 0 auto";'
    + 'return b;'
    + '}'
    + 'var links=document.createElement("span");'
    + 'links.style.cssText="flex:1 1 100%;font-size:12px;display:flex;gap:14px;flex-wrap:wrap";'
    + 'function link(label,href){'
    + 'var a=document.createElement("a");'
    + 'a.textContent=label;a.href=href;a.rel="noopener";'
    + 'a.style.cssText="color:#7aa5ff";'
    + 'return a;'
    + '}'
    + 'links.appendChild(link("Privacy Policy",CFG.privacy));'
    + 'links.appendChild(link("Terms",CFG.terms));'
    + 'if(CFG.ccpa&&CFG.doNotSell)links.appendChild(link("Do Not Sell or Share My Personal Information",CFG.doNotSell));'
    + 'el.appendChild(links);'
    + 'var no=btn("Decline",false);'
    + 'var yes=btn("Accept",true);'
    + 'no.addEventListener("click",function(){decide("denied");});'
    + 'yes.addEventListener("click",function(){decide("granted");});'
    + 'el.appendChild(no);el.appendChild(yes);'
    + 'document.body.appendChild(el);'
    + '}'
    // Public API: a site can offer "Cookie settings" anywhere.
    + 'window.__paiConsent={'
    + 'get:function(){return read();},'
    + 'accept:function(){decide("granted");},'
    + 'decline:function(){decide("denied");},'
    + 'revoke:function(){write(null);choice=null;stop();hide();},'
    + 'show:function(){choice=read();hide();if(!choice)show();},'
    + 'optedOut:optOut'
    + '};'
    + 'choice=read();'
    + 'if(choice===null&&optOut()){choice="denied";write(choice);}'
    + 'if(choice==="granted")start();'
    + 'if(!choice){'
    + 'if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",show);'
    + 'else show();'
    + '}'
    + '})();';
}

module.exports = {
  esc,
  generatePrivacyPolicy,
  generateCookieConsentScript,
  policyFacts,
  regimeFor,
  normalizeRegion,
  normalizeType
};
